### ISSUE TITLE
dat-ecosystem website_coming_soon_page

### ISSUE THREAD

**Issue by Mehrabbruno** [dat-ecosystem/organization#112]
#70

## `todo`

- [x] create a coming_soon_page_v0.0.2
   - `@input` 📦 [`navbar_v0.0.13`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1573-1913&t=i9jWdxjECWAyb6ri-4) from #72 
   - [x] read feedback
   - [x] add a cover picture for coming soon
   - [x] update tasks
   - `@output` 📦 [`coming_soon_page_web_v0.0.1`](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1744-1913&t=i9jWdxjECWAyb6ri-4) from [`comment`](https://github.com/dat-ecosystem/organization/issues/112#issuecomment-1548947083)

**Comment by Mehrabbruno** [comment]
### tasks `2023.05.16`

- create a coming_soon_page_v0.0.2  - `52min`
   - read feedback on growth page - `4min`
   - add a cover picture for coming soon
   - try to fit the fonts into grid
   - create, update tasks and worklog - `12min`
   - `@output` 📦 [timeline_page_web_v0.0.13](https://www.figma.com/file/1zBxgchAmrDGw2FDzu7uxX/dat-ecosystem-website?type=design&node-id=1766-4044&t=i9jWdxjECWAyb6ri-4)

---

### worklog

[worklog 145](https://youtu.be/mYecpVhfkHQ)

---

### feedback

---

### proposals

**Comment by serapath** [comment]
**feedback `2023.05.16`**

First feedback for the close `x` button.
Yes, i agree it does not make much sense on the "coming soon" banner.
So this is fine.
The navbar tab represents a specific program, imagine it like a "PDF".
Or even just an HTML previewer.
Or a "slide deck" program (imagine for example if the `home`, `projects`, `timeline` and `growth program` where slide decks, but each slide is a program and it's fixed.

It's a new thing. It doesn't really have any prior example i would be aware of.
But if we just create such a presentation format, we could store a file that defines the programs and content and the order in which they are displayed and then we can open that "file" with the specific viewer program, which we open 4 times (for each navbar tab).

Also, a navbar tab can also just represent another desktop. a desktop also being just yet another program. (for example the pinned "info" tab).

That way we still get something systematic that a user can learn and understand and later use for their own customized version of the page, instead of us hard coding some very dat-ecosystem webpage specific layout.

---

### regarding banner choice
I was checking back and forth and both banner proposals have pros and cons.
I agree with your argument too, but i checked back after one hour and then again after another hour and slowly things started shifting and I felt the colorful big banner is better.
So I asked Nina what she thinks and others too and they all said the colorful one is the more inviting one. It also shows nature, maybe even a bit of a wild  garden or at least national park. We also don't use that image yet and people can actually look at it for a longer time to explore the image and imagine what could all of this mean.

I think to spark imagination and to make things more friendly and interesting, let's go with the colorful banner.
The other banner we also already have on the home page, so it's not lost either.
It also can finally introduce the two helper robots :-)
